service: auth
provider:
  name: aws
  runtime: nodejs16.x
  region: ap-southeast-1
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: ./google-services.json

  ecr:
    images:
      auth:
        path: ./
        file: auth.Dockerfile

functions:
  app:
    image:
      name: auth
      command:
        - dist/apps/auth/main.js.handler
      entryPoint:
        - '/lambda-entrypoint.sh'
    timeout: 30
    events:
      - http:
          method: any
          path: /{proxy+}
      - http:
          method: any
          path: /