name: Build and deploy serverless app

on:
  push:
    branches:
      - main
jobs:
  auth-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm install -g pnpm
      - run: npm install -g serverless
      # todo: add test case
      - run: pnpm install
      - run: cd apps/auth && npx prisma generate
      - run: npx nx run auth:test
      - run: npx nx run auth:build
      - run: npx serverless deploy --config auth.serverless.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-3